### ISSUE TITLE
discover_db error

### ISSUE THREAD

**Issue by jetster426** [darkoperator/Metasploit-Plugins#10]
Sorry to be a pain, found the following error, if you could assist please:

[-] Error while running command discover_db: undefined method `datastore' for nil:NilClass

Call stack:
/usr/share/metasploit-framework/plugins/pentest.rb:1526:in block in run_aux_module' /usr/share/metasploit-framework/plugins/pentest.rb:1525:ineach'
/usr/share/metasploit-framework/plugins/pentest.rb:1525:in run_aux_module' /usr/share/metasploit-framework/plugins/pentest.rb:1647:inblock in run_version_scans'
/usr/share/metasploit-framework/vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.7.1/lib/active_record/relation/delegation.rb:46:in each' /usr/share/metasploit-framework/vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.7.1/lib/active_record/relation/delegation.rb:46:ineach'
/usr/share/metasploit-framework/plugins/pentest.rb:1598:in run_version_scans' /usr/share/metasploit-framework/plugins/pentest.rb:1072:inblock in cmd_discover_db'
/usr/share/metasploit-framework/vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.7.1/lib/active_record/relation/delegation.rb:46:in each' /usr/share/metasploit-framework/vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.7.1/lib/active_record/relation/delegation.rb:46:ineach'
/usr/share/metasploit-framework/plugins/pentest.rb:1069:in cmd_discover_db' /usr/share/metasploit-framework/lib/rex/ui/text/dispatcher_shell.rb:430:inrun_command'
/usr/share/metasploit-framework/lib/rex/ui/text/dispatcher_shell.rb:392:in block in run_single' /usr/share/metasploit-framework/lib/rex/ui/text/dispatcher_shell.rb:386:ineach'
/usr/share/metasploit-framework/lib/rex/ui/text/dispatcher_shell.rb:386:in run_single' /usr/share/metasploit-framework/lib/rex/ui/text/shell.rb:205:inrun'
/usr/share/metasploit-framework/lib/metasploit/framework/command/console.rb:48:in start' /usr/share/metasploit-framework/lib/metasploit/framework/command/base.rb:82:instart'
/usr/bin/msfconsole:48:in `

**Comment by darkoperator** [comment]
Test the last mod I did for 1.4.1 and tell me if there are any print errors of missing modules

**Comment by jetster426** [comment]
msf auxiliary(vmware_server_dir_trav) > load pentest

       ___         _          _     ___ _           _
      | _ \___ _ _| |_ ___ __| |_  | _ \ |_  _ __ _(_)_ _
      |  _/ -_) ' \  _/ -_|_-<  _| |  _/ | || / _` | | ' \
      |_| \___|_||_\__\___/__/\__| |_| |_|\_,_\__, |_|_||_|
                                              |___/

Version 1.4
Pentest plugin loaded.
by Carlos Perez (carlos_perez[at]darkoperator.com)
[*] Successfully loaded plugin: pentest
msf auxiliary(vmware_server_dir_trav) > discover_db

<-----clipped----->
[*] Error: xxx.xxx.xxx.xxx: OpenSSL::SSL::SSLError SSL_connect SYSCALL returned=5 errno=0 state=unknown state
[-] xxx.xxx.xxx.xxx: Error: SSL_connect SYSCALL returned=5 errno=0 state=unknown state
[-] xxx.xxx.xxx.xxx: File doesn't seem to exist. The upload probably failed.
[*] Scanned 1 of 1 hosts (100% complete)
[-] xxx.xxx.xxx.xxx: Error: Connection reset by peer
[-] xxx.xxx.xxx.xxx: File doesn't seem to exist. The upload probably failed.
[*] Scanned 1 of 1 hosts (100% complete)
[-] xxx.xxx.xxx.xxx: Error: The connection timed out (xxx.xxx.xxx.xxx).
[*] Scanned 1 of 1 hosts (100% complete)
[-] xxx.xxx.xxx.xxx: File doesn't seem to exist. The upload probably failed.
[*] Scanned 1 of 1 hosts (100% complete)
[-] xxx.xxx.xxx.xxx: Error: The connection timed out (xxx.xxx.xxx.xxx:443).
[-] xxx.xxx.xxx.xxx: File doesn't seem to exist. The upload probably failed.
[*] Scanned 1 of 1 hosts (100% complete)
[-] xxx.xxx.xxx.xxx: Error: Connection reset by peer
[-] xxx.xxx.xxx.xxx: File doesn't seem to exist. The upload probably failed.
[*] Scanned 1 of 1 hosts (100% complete)
[-] xxx.xxx.xxx.xxx: Error: Connection reset by peer
[-] xxx.xxx.xxx.xxx: File doesn't seem to exist. The upload probably failed.
[*] Scanned 1 of 1 hosts (100% complete)
[-] xxx.xxx.xxx.xxx: Error: The connection timed out (xxx.xxx.xxx.xxx:8443).
[-] xxx.xxx.xxx.xxx: File doesn't seem to exist. The upload probably failed.
[*] Scanned 1 of 1 hosts (100% complete)
[*] xxx.xxx.xxx.xxx - AFP xxx.xxx.xxx.xxx Scanning...
[*] Scanned 1 of 1 hosts (100% complete)
[-] xxx.xxx.xxx.xxx: Error: The connection timed out (xxx.xxx.xxx.xxx:1183).
[-] xxx.xxx.xxx.xxx: File doesn't seem to exist. The upload probably failed.
[*] Scanned 1 of 1 hosts (100% complete)

[-] Error while running command discover_db: undefined method `datastore' for nil:NilClass

Call stack:
/usr/share/metasploit-framework/plugins/pentest.rb:1526:in `block in run_aux_module'
/usr/share/metasploit-framework/plugins/pentest.rb:1525:in `each'
/usr/share/metasploit-framework/plugins/pentest.rb:1525:in `run_aux_module'
/usr/share/metasploit-framework/plugins/pentest.rb:1647:in `block in run_version_scans'
/usr/share/metasploit-framework/vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.7.1/lib/active_record/relation/delegation.rb:46:in `each'
/usr/share/metasploit-framework/vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.7.1/lib/active_record/relation/delegation.rb:46:in `each'
/usr/share/metasploit-framework/plugins/pentest.rb:1598:in `run_version_scans'
/usr/share/metasploit-framework/plugins/pentest.rb:1072:in `block in cmd_discover_db'
/usr/share/metasploit-framework/vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.7.1/lib/active_record/relation/delegation.rb:46:in `each'
/usr/share/metasploit-framework/vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.7.1/lib/active_record/relation/delegation.rb:46:in `each'
/usr/share/metasploit-framework/plugins/pentest.rb:1069:in `cmd_discover_db'
/usr/share/metasploit-framework/lib/rex/ui/text/dispatcher_shell.rb:430:in `run_command'
/usr/share/metasploit-framework/lib/rex/ui/text/dispatcher_shell.rb:392:in `block in run_single'
/usr/share/metasploit-framework/lib/rex/ui/text/dispatcher_shell.rb:386:in `each'
/usr/share/metasploit-framework/lib/rex/ui/text/dispatcher_shell.rb:386:in `run_single'
/usr/share/metasploit-framework/lib/rex/ui/text/shell.rb:205:in `run'
/usr/share/metasploit-framework/lib/metasploit/framework/command/console.rb:48:in `start'
/usr/share/metasploit-framework/lib/metasploit/framework/command/base.rb:82:in `start'
/usr/bin/msfconsole:48:in `<main>'

[*] Scanned 1 of 1 hosts (100% complete)
[*] Scanned 1 of 1 hosts (100% complete)
[*] Scanned 1 of 1 hosts (100% complete)
[*] Scanned 1 of 1 hosts (100% complete)
<-----clipped----->

**Comment by darkoperator** [comment]
Ok version 1.4.1 I pushed this morning should address that.

**Comment by jetster426** [comment]
all good now thank you
