### ISSUE TITLE
Failed to load plugin ... :cannot load such file -- twitter

### ISSUE THREAD

**Issue by jdr0dn3y** [darkoperator/Metasploit-Plugins#6]
Using version 4.6.2 of twitter gem, and 4.0.0 of twitter gem. refuses to load.

Which twitter gem do you have this working with?

**Comment by forkmind** [comment]
Same issue with R7 installer on ubuntu and preinstalled framework on kali.

**Comment by darkoperator** [comment]
Because Metasploit no longer allows the loading of gems not in its gem file and if you add the twitter gem after an msfupdate it will be overwritten

**Comment by forkmind** [comment]
okay so [this](https://funoverip.net/2012/10/metasploit-plugin-email-notification/) plugin won't works too :/ 
Do you know then a workaround to be notified when a session is open ?

**Comment by darkoperator** [comment]
It may work of it does not use gem not included woth framework. You can always add a gem to the gemfile but just be aware when you update that it will be overwritten
