### ISSUE TITLE
Pentest Plugin Not Working

### ISSUE THREAD

**Issue by davehardy20** [darkoperator/Metasploit-Plugins#7]
Hi Carlos,

Since I updated my git version of the framework;

Framework: 4.6.0-dev
Console  : 4.6.0-dev.15168

the network_discover part of the pentest plugin doesn't work any more;

2013-04-10 09:50:42 +0100 S:0 J:1 msf auxiliary(udp_sweep) > network_discover -r 192.168.10.0/24
[*] Generating list of ports used by Auxiliary Modules
[-] Error while running command network_discover: undefined method `new' for "**SYMBOLIC**":String

Call stack:
/root/.msf4/plugins/pentest.rb:1539:in `block in get_tcp_port_list'
/opt/framework/lib/msf/core/module_set.rb:78:in`each'
/opt/framework/lib/msf/core/module_set.rb:78:in `each'
/root/.msf4/plugins/pentest.rb:1539:in`collect'
/root/.msf4/plugins/pentest.rb:1539:in `get_tcp_port_list'
/root/.msf4/plugins/pentest.rb:1395:in`cmd_network_discover'
/opt/framework/lib/rex/ui/text/dispatcher_shell.rb:427:in `run_command'
/opt/framework/lib/rex/ui/text/dispatcher_shell.rb:389:in`block in run_single'
/opt/framework/lib/rex/ui/text/dispatcher_shell.rb:383:in `each'
/opt/framework/lib/rex/ui/text/dispatcher_shell.rb:383:in`run_single'
/opt/framework/lib/rex/ui/text/shell.rb:200:in `run'
./msfconsole:169:in`<main>'
2013-04-10 10:34:23 +0100 S:0 J:0 msf auxiliary(udp_sweep) > 

I'm guessing something changed when the update was applied, I know the ruby gems were updated too as I had to re-run bundle install after the update.

Thanks in advance

Dave

**Comment by darkoperator** [comment]
just pushed version 1.4 with fixes.
