### ISSUE TITLE
Error running discover_db with pentest plugin

### ISSUE THREAD

**Issue by jetster426** [darkoperator/Metasploit-Plugins#9]
Morning wondering if you could assist please.
I have updated my metasploit install to 4.13.0-dev
I tried to use the plugin and tried discover_db and network_discover, following the update the following error was returned:
[-] Error while running command network_discover: undefined method `find_all_by_state' for #<Mdm::Host::ActiveRecord_Associations_CollectionProxy:0x007f4419531448>

Call stack:
/usr/share/metasploit-framework/vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.7.1/lib/active_record/relation/delegation.rb:136:in `method_missing'
/usr/share/metasploit-framework/vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.7.1/lib/active_record/relation/delegation.rb:99:in `method_missing'
/usr/share/metasploit-framework/plugins/pentest.rb:1409:in `cmd_network_discover'
/usr/share/metasploit-framework/lib/rex/ui/text/dispatcher_shell.rb:430:in `run_command'
/usr/share/metasploit-framework/lib/rex/ui/text/dispatcher_shell.rb:392:in `block in run_single'
/usr/share/metasploit-framework/lib/rex/ui/text/dispatcher_shell.rb:386:in `each'
/usr/share/metasploit-framework/lib/rex/ui/text/dispatcher_shell.rb:386:in `run_single'
/usr/share/metasploit-framework/lib/rex/ui/text/shell.rb:205:in `run'
/usr/share/metasploit-framework/lib/metasploit/framework/command/console.rb:48:in `start'
/usr/share/metasploit-framework/lib/metasploit/framework/command/base.rb:82:in `start'
/usr/bin/msfconsole:48:in `<main>'

Any assistance would be greatly appreciated.
Thanks

**Comment by darkoperator** [comment]
Will push a fix for this later today. Thank you for reporting it

**Comment by jetster426** [comment]
Thanks for the quick response Carlos, here is the error for the discover_db:
msf > discover_db
[-] Error while running command discover_db: undefined method `find_all_by_state' for #<Mdm::Service::ActiveRecord_Associations_CollectionProxy:0x007f0c746d9c00>

Call stack:
/usr/share/metasploit-framework/vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.7.1/lib/active_record/relation/delegation.rb:136:in `method_missing'
/usr/share/metasploit-framework/vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.7.1/lib/active_record/relation/delegation.rb:99:in `method_missing'
/usr/share/metasploit-framework/plugins/pentest.rb:1071:in `block in cmd_discover_db'
/usr/share/metasploit-framework/vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.7.1/lib/active_record/relation/delegation.rb:46:in `each'
/usr/share/metasploit-framework/vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.7.1/lib/active_record/relation/delegation.rb:46:in `each'
/usr/share/metasploit-framework/plugins/pentest.rb:1069:in `cmd_discover_db'
/usr/share/metasploit-framework/lib/rex/ui/text/dispatcher_shell.rb:430:in `run_command'
/usr/share/metasploit-framework/lib/rex/ui/text/dispatcher_shell.rb:392:in `block in run_single'
/usr/share/metasploit-framework/lib/rex/ui/text/dispatcher_shell.rb:386:in `each'
/usr/share/metasploit-framework/lib/rex/ui/text/dispatcher_shell.rb:386:in `run_single'
/usr/share/metasploit-framework/lib/rex/ui/text/shell.rb:205:in `run'
/usr/share/metasploit-framework/lib/metasploit/framework/command/console.rb:48:in `start'
/usr/share/metasploit-framework/lib/metasploit/framework/command/base.rb:82:in `start'
/usr/bin/msfconsole:48:in `<main>'

Regards
JET

**Comment by darkoperator** [comment]
Yep that method was removed I switched all code to the proper one, but had to go out and was not able to finish testing to push the code out

**Comment by darkoperator** [comment]
just pushed version 1.4 with a fix

**Comment by jetster426** [comment]
Thanks very much for the fast turn around, works like a dream.

**Comment by jetster426** [comment]
Sorry to be a pain, found a new error:

[-] Error while running command discover_db: undefined method `datastore' for nil:NilClass

Call stack:
/usr/share/metasploit-framework/plugins/pentest.rb:1526:in `block in run_aux_module'
/usr/share/metasploit-framework/plugins/pentest.rb:1525:in `each'
/usr/share/metasploit-framework/plugins/pentest.rb:1525:in `run_aux_module'
/usr/share/metasploit-framework/plugins/pentest.rb:1647:in `block in run_version_scans'
/usr/share/metasploit-framework/vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.7.1/lib/active_record/relation/delegation.rb:46:in `each'
/usr/share/metasploit-framework/vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.7.1/lib/active_record/relation/delegation.rb:46:in `each'
/usr/share/metasploit-framework/plugins/pentest.rb:1598:in `run_version_scans'
/usr/share/metasploit-framework/plugins/pentest.rb:1072:in `block in cmd_discover_db'
/usr/share/metasploit-framework/vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.7.1/lib/active_record/relation/delegation.rb:46:in `each'
/usr/share/metasploit-framework/vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.7.1/lib/active_record/relation/delegation.rb:46:in `each'
/usr/share/metasploit-framework/plugins/pentest.rb:1069:in `cmd_discover_db'
/usr/share/metasploit-framework/lib/rex/ui/text/dispatcher_shell.rb:430:in `run_command'
/usr/share/metasploit-framework/lib/rex/ui/text/dispatcher_shell.rb:392:in `block in run_single'
/usr/share/metasploit-framework/lib/rex/ui/text/dispatcher_shell.rb:386:in `each'
/usr/share/metasploit-framework/lib/rex/ui/text/dispatcher_shell.rb:386:in `run_single'
/usr/share/metasploit-framework/lib/rex/ui/text/shell.rb:205:in `run'
/usr/share/metasploit-framework/lib/metasploit/framework/command/console.rb:48:in `start'
/usr/share/metasploit-framework/lib/metasploit/framework/command/base.rb:82:in `start'
/usr/bin/msfconsole:48:in `<main>'

**Comment by darkoperator** [comment]
What was the command line of the command that generated the error?
